M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu22.04.1} date 2024-11-01T17:47:31+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-01T17:47:31+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X138.5Y-103.0
T2
X117.25Y-89.0
X159.75Y-89.0
M30
